export enum ePAYMENTSMETHOD {
  CASH = "CASH",
  MPESA = "MPESA"
}
export enum ePAYMENTSTUTUS {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED"
}
export enum eSTATUS {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED"
}