/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RideioRouteImport } from './routes/rideio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as RideioUserDashboardRouteImport } from './routes/rideio/user/dashboard'
import { Route as RideioDriverDashboardRouteImport } from './routes/rideio/driver/dashboard'
import { Route as RideioAdminDashboardRouteImport } from './routes/rideio/admin/dashboard'
import { Route as AuthUserSigninRouteImport } from './routes/auth/user/signin'
import { Route as AuthDriverRegisterRouteImport } from './routes/auth/driver/register'
import { Route as AuthAdminLoginRouteImport } from './routes/auth/admin/login'

const RideioRoute = RideioRouteImport.update({
  id: '/rideio',
  path: '/rideio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const RideioUserDashboardRoute = RideioUserDashboardRouteImport.update({
  id: '/user/dashboard',
  path: '/user/dashboard',
  getParentRoute: () => RideioRoute,
} as any)
const RideioDriverDashboardRoute = RideioDriverDashboardRouteImport.update({
  id: '/driver/dashboard',
  path: '/driver/dashboard',
  getParentRoute: () => RideioRoute,
} as any)
const RideioAdminDashboardRoute = RideioAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => RideioRoute,
} as any)
const AuthUserSigninRoute = AuthUserSigninRouteImport.update({
  id: '/auth/user/signin',
  path: '/auth/user/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDriverRegisterRoute = AuthDriverRegisterRouteImport.update({
  id: '/auth/driver/register',
  path: '/auth/driver/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminLoginRoute = AuthAdminLoginRouteImport.update({
  id: '/auth/admin/login',
  path: '/auth/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rideio': typeof RideioRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/driver/register': typeof AuthDriverRegisterRoute
  '/auth/user/signin': typeof AuthUserSigninRoute
  '/rideio/admin/dashboard': typeof RideioAdminDashboardRoute
  '/rideio/driver/dashboard': typeof RideioDriverDashboardRoute
  '/rideio/user/dashboard': typeof RideioUserDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rideio': typeof RideioRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/driver/register': typeof AuthDriverRegisterRoute
  '/auth/user/signin': typeof AuthUserSigninRoute
  '/rideio/admin/dashboard': typeof RideioAdminDashboardRoute
  '/rideio/driver/dashboard': typeof RideioDriverDashboardRoute
  '/rideio/user/dashboard': typeof RideioUserDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rideio': typeof RideioRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/driver/register': typeof AuthDriverRegisterRoute
  '/auth/user/signin': typeof AuthUserSigninRoute
  '/rideio/admin/dashboard': typeof RideioAdminDashboardRoute
  '/rideio/driver/dashboard': typeof RideioDriverDashboardRoute
  '/rideio/user/dashboard': typeof RideioUserDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rideio'
    | '/demo/tanstack-query'
    | '/auth/admin/login'
    | '/auth/driver/register'
    | '/auth/user/signin'
    | '/rideio/admin/dashboard'
    | '/rideio/driver/dashboard'
    | '/rideio/user/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rideio'
    | '/demo/tanstack-query'
    | '/auth/admin/login'
    | '/auth/driver/register'
    | '/auth/user/signin'
    | '/rideio/admin/dashboard'
    | '/rideio/driver/dashboard'
    | '/rideio/user/dashboard'
  id:
    | '__root__'
    | '/'
    | '/rideio'
    | '/demo/tanstack-query'
    | '/auth/admin/login'
    | '/auth/driver/register'
    | '/auth/user/signin'
    | '/rideio/admin/dashboard'
    | '/rideio/driver/dashboard'
    | '/rideio/user/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RideioRoute: typeof RideioRouteWithChildren
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  AuthAdminLoginRoute: typeof AuthAdminLoginRoute
  AuthDriverRegisterRoute: typeof AuthDriverRegisterRoute
  AuthUserSigninRoute: typeof AuthUserSigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rideio': {
      id: '/rideio'
      path: '/rideio'
      fullPath: '/rideio'
      preLoaderRoute: typeof RideioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rideio/user/dashboard': {
      id: '/rideio/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/rideio/user/dashboard'
      preLoaderRoute: typeof RideioUserDashboardRouteImport
      parentRoute: typeof RideioRoute
    }
    '/rideio/driver/dashboard': {
      id: '/rideio/driver/dashboard'
      path: '/driver/dashboard'
      fullPath: '/rideio/driver/dashboard'
      preLoaderRoute: typeof RideioDriverDashboardRouteImport
      parentRoute: typeof RideioRoute
    }
    '/rideio/admin/dashboard': {
      id: '/rideio/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/rideio/admin/dashboard'
      preLoaderRoute: typeof RideioAdminDashboardRouteImport
      parentRoute: typeof RideioRoute
    }
    '/auth/user/signin': {
      id: '/auth/user/signin'
      path: '/auth/user/signin'
      fullPath: '/auth/user/signin'
      preLoaderRoute: typeof AuthUserSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/driver/register': {
      id: '/auth/driver/register'
      path: '/auth/driver/register'
      fullPath: '/auth/driver/register'
      preLoaderRoute: typeof AuthDriverRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin/login': {
      id: '/auth/admin/login'
      path: '/auth/admin/login'
      fullPath: '/auth/admin/login'
      preLoaderRoute: typeof AuthAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RideioRouteChildren {
  RideioAdminDashboardRoute: typeof RideioAdminDashboardRoute
  RideioDriverDashboardRoute: typeof RideioDriverDashboardRoute
  RideioUserDashboardRoute: typeof RideioUserDashboardRoute
}

const RideioRouteChildren: RideioRouteChildren = {
  RideioAdminDashboardRoute: RideioAdminDashboardRoute,
  RideioDriverDashboardRoute: RideioDriverDashboardRoute,
  RideioUserDashboardRoute: RideioUserDashboardRoute,
}

const RideioRouteWithChildren =
  RideioRoute._addFileChildren(RideioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RideioRoute: RideioRouteWithChildren,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  AuthAdminLoginRoute: AuthAdminLoginRoute,
  AuthDriverRegisterRoute: AuthDriverRegisterRoute,
  AuthUserSigninRoute: AuthUserSigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
