/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserDashboardRouteImport } from './routes/user/dashboard'
import { Route as DriverDashboardRouteImport } from './routes/driver/dashboard'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AuthUserSigninRouteImport } from './routes/auth/user/signin'
import { Route as AuthDriverRegisterRouteImport } from './routes/auth/driver/register'
import { Route as AuthAdminLoginRouteImport } from './routes/auth/admin/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/user/dashboard',
  path: '/user/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDashboardRoute = DriverDashboardRouteImport.update({
  id: '/driver/dashboard',
  path: '/driver/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUserSigninRoute = AuthUserSigninRouteImport.update({
  id: '/auth/user/signin',
  path: '/auth/user/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDriverRegisterRoute = AuthDriverRegisterRouteImport.update({
  id: '/auth/driver/register',
  path: '/auth/driver/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminLoginRoute = AuthAdminLoginRouteImport.update({
  id: '/auth/admin/login',
  path: '/auth/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/driver/register': typeof AuthDriverRegisterRoute
  '/auth/user/signin': typeof AuthUserSigninRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/driver/register': typeof AuthDriverRegisterRoute
  '/auth/user/signin': typeof AuthUserSigninRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/driver/register': typeof AuthDriverRegisterRoute
  '/auth/user/signin': typeof AuthUserSigninRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/demo/tanstack-query'
    | '/driver/dashboard'
    | '/user/dashboard'
    | '/auth/admin/login'
    | '/auth/driver/register'
    | '/auth/user/signin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/dashboard'
    | '/demo/tanstack-query'
    | '/driver/dashboard'
    | '/user/dashboard'
    | '/auth/admin/login'
    | '/auth/driver/register'
    | '/auth/user/signin'
  id:
    | '__root__'
    | '/'
    | '/admin/dashboard'
    | '/demo/tanstack-query'
    | '/driver/dashboard'
    | '/user/dashboard'
    | '/auth/admin/login'
    | '/auth/driver/register'
    | '/auth/user/signin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DriverDashboardRoute: typeof DriverDashboardRoute
  UserDashboardRoute: typeof UserDashboardRoute
  AuthAdminLoginRoute: typeof AuthAdminLoginRoute
  AuthDriverRegisterRoute: typeof AuthDriverRegisterRoute
  AuthUserSigninRoute: typeof AuthUserSigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/dashboard': {
      id: '/driver/dashboard'
      path: '/driver/dashboard'
      fullPath: '/driver/dashboard'
      preLoaderRoute: typeof DriverDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/user/signin': {
      id: '/auth/user/signin'
      path: '/auth/user/signin'
      fullPath: '/auth/user/signin'
      preLoaderRoute: typeof AuthUserSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/driver/register': {
      id: '/auth/driver/register'
      path: '/auth/driver/register'
      fullPath: '/auth/driver/register'
      preLoaderRoute: typeof AuthDriverRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin/login': {
      id: '/auth/admin/login'
      path: '/auth/admin/login'
      fullPath: '/auth/admin/login'
      preLoaderRoute: typeof AuthAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DriverDashboardRoute: DriverDashboardRoute,
  UserDashboardRoute: UserDashboardRoute,
  AuthAdminLoginRoute: AuthAdminLoginRoute,
  AuthDriverRegisterRoute: AuthDriverRegisterRoute,
  AuthUserSigninRoute: AuthUserSigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
